#!/bin/sh
set -e
APPDIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
for hook in "$APPDIR"/apprun-hooks/*.sh; do
    [ -f "$hook" ] && . "$hook"
done
export PYTHONHOME="$APPDIR/usr"
export PYTHONPATH="$APPDIR/usr/lib/@PYTHON_VERSION@/dist-packages"
export PATH="$APPDIR/usr/bin:$PATH"
exec "$APPDIR/usr/bin/python3" "$APPDIR/usr/share/mediashelf/mediashelf.py" "$@"
